name: JMeter Performance Test

on:
  push:
    branches:
      - main  # adjust this to match your main branch

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: JMeter Test
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: ./Testcase/ThreadGroup.jmx
          args: "-l /reports/result.jtl -e -o ./reports/html/"

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-html-reports
          path: reports
          if-no-files-found: error    