name: JMeter Performance Test

on:
  push:
    branches:
      - main  # adjust this to match your main branch

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'  # adjust Java version as per your JMeter requirements

      - name: Run JMeter Performance Test
        run: |
          wget -q https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz
          tar -xzf apache-jmeter-5.4.1.tgz
          ./apache-jmeter-5.4.1/bin/jmeter -n -t Testcase/ThreadGroup.jmx -l Report/new.jtl -e -o Report/skip.html

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: ./Report  # adjust path if your results file is saved elsewhere
